In [2]:
import numpy as np

In [4]:
np.loadtxt(fname='inflammation-01.csv', delimiter=',')

array([[ 0.,  0.,  1.,  3.,  1.,  2.,  4.,  7.,  8.,  3.,  3.,  3., 10.,
         5.,  7.,  4.,  7.,  7., 12., 18.,  6., 13., 11., 11.,  7.,  7.,
         4.,  6.,  8.,  8.,  4.,  4.,  5.,  7.,  3.,  4.,  2.,  3.,  0.,
         0.],
       [ 0.,  1.,  2.,  1.,  2.,  1.,  3.,  2.,  2.,  6., 10., 11.,  5.,
         9.,  4.,  4.,  7., 16.,  8.,  6., 18.,  4., 12.,  5., 12.,  7.,
        11.,  5., 11.,  3.,  3.,  5.,  4.,  4.,  5.,  5.,  1.,  1.,  0.,
         1.],
       [ 0.,  1.,  1.,  3.,  3.,  2.,  6.,  2.,  5.,  9.,  5.,  7.,  4.,
         5.,  4., 15.,  5., 11.,  9., 10., 19., 14., 12., 17.,  7., 12.,
        11.,  7.,  4.,  2., 10.,  5.,  4.,  2.,  2.,  3.,  2.,  2.,  1.,
         1.]])

In [5]:
data = np.loadtxt(fname='inflammation-01.csv', delimiter=',')

In [15]:
print(data)

[[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
  12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
   2.  3.  0.  0.]
 [ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6. 10. 11.  5.  9.  4.  4.  7. 16.
   8.  6. 18.  4. 12.  5. 12.  7. 11.  5. 11.  3.  3.  5.  4.  4.  5.  5.
   1.  1.  0.  1.]
 [ 0.  1.  1.  3.  3.  2.  6.  2.  5.  9.  5.  7.  4.  5.  4. 15.  5. 11.
   9. 10. 19. 14. 12. 17.  7. 12. 11.  7.  4.  2. 10.  5.  4.  2.  2.  3.
   2.  2.  1.  1.]]


In [16]:
print(type(data))

<class 'numpy.ndarray'>


In [18]:
"""
Data Type
A Numpy array contains one or more elements of the same type. 
The type function will only tell you that a variable is a NumPy array 
but won’t tell you the type of thing inside the array. 
We can find out the type of the data contained in the NumPy array.
"""
print(data.dtype)
# This tells us that the NumPy array’s elements are floating-point numbers.

float64


In [19]:
print(data.shape)

(3, 40)


In [20]:
print('first value in data:', data[0, 0])

first value in data: 0.0


In [22]:
print('middle value in data:', data[2, 19])

middle value in data: 10.0


In [23]:
"""
In the Corner
What may also surprise you is that when Python displays an array, 
it shows the element with index [0, 0] in the upper left corner rather 
than the lower left. This is consistent with the way mathematicians 
draw matrices but different from the Cartesian coordinates. 
The indices are (row, column) instead of (column, row) for the same reason,
which can be confusing when plotting data.
"""

'\nIn the Corner\nWhat may also surprise you is that when Python displays an array, \nit shows the element with index [0, 0] in the upper left corner rather \nthan the lower left. This is consistent with the way mathematicians \ndraw matrices but different from the Cartesian coordinates. \nThe indices are (row, column) instead of (column, row) for the same reason,\nwhich can be confusing when plotting data.\n'

In [24]:
# Slicing data
"""
An index like [30, 20] selects a single element of an array, 
but we can select whole sections as well. For example, 
we can select the first ten days (columns) of values for the first 
four patients (rows) like this:
"""
print(data[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]]
