In [2]:
import numpy as np

In [3]:
np.loadtxt(fname='inflammation-01.csv', delimiter=',')

array([[ 0.,  0.,  1.,  3.,  1.,  2.,  4.,  7.,  8.,  3.,  3.,  3., 10.,
         5.,  7.,  4.,  7.,  7., 12., 18.,  6., 13., 11., 11.,  7.,  7.,
         4.,  6.,  8.,  8.,  4.,  4.,  5.,  7.,  3.,  4.,  2.,  3.,  0.,
         0.],
       [ 0.,  1.,  2.,  1.,  2.,  1.,  3.,  2.,  2.,  6., 10., 11.,  5.,
         9.,  4.,  4.,  7., 16.,  8.,  6., 18.,  4., 12.,  5., 12.,  7.,
        11.,  5., 11.,  3.,  3.,  5.,  4.,  4.,  5.,  5.,  1.,  1.,  0.,
         1.],
       [ 0.,  1.,  1.,  3.,  3.,  2.,  6.,  2.,  5.,  9.,  5.,  7.,  4.,
         5.,  4., 15.,  5., 11.,  9., 10., 19., 14., 12., 17.,  7., 12.,
        11.,  7.,  4.,  2., 10.,  5.,  4.,  2.,  2.,  3.,  2.,  2.,  1.,
         1.]])

In [4]:
data = np.loadtxt(fname='inflammation-01.csv', delimiter=',')

In [5]:
print(data)

[[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
  12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
   2.  3.  0.  0.]
 [ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6. 10. 11.  5.  9.  4.  4.  7. 16.
   8.  6. 18.  4. 12.  5. 12.  7. 11.  5. 11.  3.  3.  5.  4.  4.  5.  5.
   1.  1.  0.  1.]
 [ 0.  1.  1.  3.  3.  2.  6.  2.  5.  9.  5.  7.  4.  5.  4. 15.  5. 11.
   9. 10. 19. 14. 12. 17.  7. 12. 11.  7.  4.  2. 10.  5.  4.  2.  2.  3.
   2.  2.  1.  1.]]


In [6]:
print(type(data))

<class 'numpy.ndarray'>


In [7]:
"""
Data Type
A Numpy array contains one or more elements of the same type. 
The type function will only tell you that a variable is a NumPy array 
but won’t tell you the type of thing inside the array. 
We can find out the type of the data contained in the NumPy array.
"""
print(data.dtype)
# This tells us that the NumPy array’s elements are floating-point numbers.

float64


In [8]:
print(data.shape)

(3, 40)


In [9]:
print('first value in data:', data[0, 0])

first value in data: 0.0


In [10]:
print('middle value in data:', data[2, 19])

middle value in data: 10.0


In [11]:
"""
In the Corner
What may also surprise you is that when Python displays an array, 
it shows the element with index [0, 0] in the upper left corner rather 
than the lower left. This is consistent with the way mathematicians 
draw matrices but different from the Cartesian coordinates. 
The indices are (row, column) instead of (column, row) for the same reason,
which can be confusing when plotting data.
"""

'\nIn the Corner\nWhat may also surprise you is that when Python displays an array, \nit shows the element with index [0, 0] in the upper left corner rather \nthan the lower left. This is consistent with the way mathematicians \ndraw matrices but different from the Cartesian coordinates. \nThe indices are (row, column) instead of (column, row) for the same reason,\nwhich can be confusing when plotting data.\n'

In [12]:
# Slicing data
"""
An index like [30, 20] selects a single element of an array, 
but we can select whole sections as well. For example, 
we can select the first ten days (columns) of values for the first 
four patients (rows) like this:
"""
print(data[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]]


In [14]:
small = data[:3, 36:]
print(f'small is: \n{small}')

small is: 
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [15]:
# find the average inflamation for all patients on all days
print(np.mean(data))

5.658333333333333


In [16]:
import time
print(time.ctime())

Tue Jun 16 01:37:11 2026


In [19]:
maxval, minval, stdval = np.max(data), np.min(data), np.std(data)
print(f"""maximum inflamation: {maxval}
minimum inflamation: {minval}
standard inflamation: {stdval}
""")

maximum inflamation: 19.0
minimum inflamation: 0.0
standard inflamation: 4.352194529455482



In [22]:
help(np.absolute)

Help on ufunc in module numpy:

absolute = <ufunc 'absolute'>
    absolute(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Calculate the absolute value element-wise.

    ``np.abs`` is a shorthand for this function.

    Parameters
    ----------
    x : array_like
        Input array.
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out

In [24]:
patient_0 = data[0, :]
print('maximum inflamation for patient 0:', np.max(patient_0))

maximum inflamation for patient 0: 18.0


In [26]:
print('maximum inflamation for patient 2:', np.max(data[2, :]))

maximum inflamation for patient 2: 19.0


In [27]:
print(np.max(data, axis=1))

[18. 18. 19.]


In [28]:
print(np.max(data, axis=1).shape)

(3,)


In [29]:
print(np.mean(data, axis=0))

[ 0.          0.66666667  1.33333333  2.33333333  2.          1.66666667
  4.33333333  3.66666667  5.          6.          6.          7.
  6.33333333  6.33333333  5.          7.66666667  6.33333333 11.33333333
  9.66666667 11.33333333 14.33333333 10.33333333 11.66666667 11.
  8.66666667  8.66666667  8.66666667  6.          7.66666667  4.33333333
  5.66666667  4.66666667  4.33333333  4.33333333  3.33333333  4.
  1.66666667  2.          0.33333333  0.66666667]


In [30]:
print(np.mean(data, axis=0).shape)

(40,)


In [31]:
print(np.mean(data, axis=1))

[5.45  5.425 6.1  ]


In [32]:
el = 'oxygen'
print('first three characters:', el[0:3])
print('last three characters:', el[3:6])

first three characters: oxy
last three characters: gen


In [35]:
print(el[:4], el[4:], el[:])

oxyg en oxygen


In [36]:
print(el[-1], el[-2])

n e


In [40]:
print(el[1:-1])

xyge


In [41]:
print(el[-3:])

gen


In [42]:
el = 'carpentry'
print(el[-3:])

try


In [43]:
el = 'clone'
print(el[-3:])

one


In [44]:
el = 'hi'
print(el[-3:])

hi


In [46]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('A = \n', A)

A = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
B = np.hstack([A, A])
print('B = \n', B)

B = 
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


In [48]:
C = np.vstack([A, A])
print('C = \n', C)

C = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
print(A.shape)

(3, 3)


In [81]:
print(A[:, 1:].shape)
print(A[:, 1:])

(3, 2)
[[2 3]
 [5 6]
 [8 9]]


In [76]:
D = np.hstack((
    A[:, :1],
    A[:, -1:]
))
print('D = \n', D)

D = 
 [[1 3]
 [4 6]
 [7 9]]


In [82]:
D = np.delete(arr=A, obj=1, axis=1)
print('D = \n', D)

D = 
 [[1 3]
 [4 6]
 [7 9]]
